DROP TABLE IF EXISTS livros_autores;
DROP TABLE IF EXISTS nacionalidades;
DROP TABLE IF EXISTS livros_editoras;
DROP TABLE IF EXISTS livros_etiquetas;
DROP TABLE IF EXISTS livros;
DROP TABLE IF EXISTS autores;
DROP TABLE IF EXISTS editoras;
DROP TABLE IF EXISTS identificadores;

CREATE TABLE livros (
	ISBN NUMERIC(13) PRIMARY KEY NOT NULL,
	TITULO TEXT NOT NULL,
	EDICAO INT,
	IDIOMA TEXT NOT NULL,
	DATA_LANCAMENTO DATE,
	DATA_COMPRA DATE
);

CREATE TABLE autores (
	NOME TEXT NOT NULL UNIQUE,
	APELIDO TEXT NOT NULL UNIQUE,
	SEXO CHAR(1) NOT NULL,
	DATA_NASCIMENTO DATE,
	PRIMARY KEY (NOME, APELIDO)
);

CREATE TABLE editoras (
	NOME TEXT PRIMARY KEY NOT NULL,
	DATA_FUNDACAO DATE,
	PAIS TEXT
);

CREATE TABLE identificadores (
	ETIQUETA TEXT PRIMARY KEY NOT NULL
);

CREATE TABLE livros_autores (
	ISBN NUMERIC(13) NOT NULL,
	NOME_AUTOR TEXT NOT NULL,
	APELIDO_AUTOR TEXT NOT NULL,
	PRIMARY KEY (ISBN, NOME_AUTOR, APELIDO_AUTOR),
	FOREIGN KEY (ISBN) REFERENCES livros(ISBN),
	FOREIGN KEY (NOME_AUTOR) REFERENCES autores(NOME),
	FOREIGN KEY (APELIDO_AUTOR) REFERENCES autores(APELIDO)
);

CREATE TABLE nacionalidades (
	NOME_AUTOR TEXT NOT NULL,
	APELIDO_AUTOR TEXT NOT NULL,
	NACIONALIDADE TEXT NOT NULL,
	PRIMARY KEY (NOME_AUTOR, APELIDO_AUTOR, NACIONALIDADE),
	FOREIGN KEY (NOME_AUTOR) REFERENCES autores(NOME),
	FOREIGN KEY (APELIDO_AUTOR) REFERENCES autores(APELIDO)
);

CREATE TABLE livros_editoras (
	ISBN NUMERIC(13) PRIMARY KEY NOT NULL,
	NOME_EDITORA TEXT NOT NULL,
	FOREIGN KEY (ISBN) REFERENCES livros(ISBN),
	FOREIGN KEY (NOME_EDITORA) REFERENCES editoras(NOME)
);

CREATE TABLE livros_etiquetas (
	ISBN NUMERIC(13) NOT NULL,
	ETIQUETA TEXT NOT NULL,
	PRIMARY KEY (ISBN, ETIQUETA),
	FOREIGN KEY (ISBN) REFERENCES livros(ISBN),
	FOREIGN KEY (ETIQUETA) REFERENCES identificadores(ETIQUETA)
);
